#!/usr/bin/env bash

test -d "node_modules" || exit 1

echo $(date)

cp node_modules/@trabpukcip/godsmack/templates/.editorconfig.template .editorconfig
cp node_modules/@trabpukcip/godsmack/templates/.gitignore.template .gitignore
cp node_modules/@trabpukcip/godsmack/templates/tsconfig.json.template tsconfig.json

mkdir src
cp node_modules/@trabpukcip/godsmack/templates/main.ts.template src/main.ts
cp node_modules/@trabpukcip/godsmack/templates/app.ts.template src/app.ts
mkdir src/controllers
cp node_modules/@trabpukcip/godsmack/templates/controller.ts.template src/controllers/acontroller.ts
mkdir src/interfaces
mkdir src/models
mkdir src/repo
mkdir src/services
cp node_modules/@trabpukcip/godsmack/templates/service.ts.template src/services/aservice.ts

mkdir www
cp node_modules/@trabpukcip/godsmack/templates/index.html.template www/index.html

yarn add --dev typescript tslib ts-node ts-node-dev mocha chai @types/node @types/mocha @types/chai
