#!/usr/bin/env bash

test -d "node_modules" || exit 1

echo $(date)

cp node_modules/@trabpukcip/godsmack/templates/.editorconfig.template .editorconfig
cp node_modules/@trabpukcip/godsmack/templates/.gitignore.template .gitignore
cp node_modules/@trabpukcip/godsmack/templates/tsconfig.json.template tsconfig.json
cp node_modules/@trabpukcip/godsmack/templates/tsoa.json.template tsoa.json

mkdir src
cp node_modules/@trabpukcip/godsmack/templates/main.ts.template src/main.ts
cp node_modules/@trabpukcip/godsmack/templates/app.ts.template src/app.ts
cp node_modules/@trabpukcip/godsmack/templates/tsoa/ioc.ts.template src/ioc.ts
mkdir src/controllers
cp node_modules/@trabpukcip/godsmack/templates/controller.ts.template src/controllers/acontroller.ts
mkdir src/interfaces
mkdir src/models
mkdir src/repo
mkdir src/services
cp node_modules/@trabpukcip/godsmack/templates/service.ts.template src/services/aservice.ts
mkdir src/middleware
cp node_modules/@trabpukcip/godsmack/templates/tsoa/auth.ts.template src/middleware/auth.ts
mkdir src/generated
cp node_modules/@trabpukcip/godsmack/templates/tsoa/routes.template.hbs.template src/templates/routes.template.hbs
cp node_modules/@trabpukcip/godsmack/templates/tsoa/routes.ts.template src/generated/routes.ts

mkdir www
cp node_modules/@trabpukcip/godsmack/templates/index.html.template www/index.html

yarn add --dev tsoa typescript tslib ts-node ts-node-dev @openapitools/openapi-generator-cli graphql type-graphql mocha chai @types/node @types/mocha @types/chai
