#!/usr/bin/env bash

echo $(date)
PROJECT_DIR=$(cat tsconfig.json | grep \"rootDir\" | awk '{printf $2}' | cut -d '"' -f2)
$PWD/node_modules/.bin/ts-node -C ttypescript -P tsconfig.json $PROJECT_DIR/main.ts
