import type { IApplication } from './IApplication';

/**
 * Application Client interface. Used to register
 * middleware and other effects with the main
 * Application instance.
 *
 * @export
 * @interface IClient
 */
export interface IClient {
  /**
   * Sets up Client middleware to serve an autogenerated TS
   * client from the specified endoint. The client has all
   * the controllers registered to the application available
   * as generated IClientAdapter implementations.
   *
   * @param {IApplication} app
   * @param {string} endpoint
   * @returns {this}
   * @memberof IClient
   */
  applyMiddleware(app: IApplication, endpoint?: string): this
}
